### ISSUE TITLE
Circular structure error

### ISSUE THREAD

**Issue by loleg** [hackathons-ftw/dridbot#1]
First [filed upstream](https://github.com/schoolofdata-ch/sodabot/issues/7) this is still happening, but only once a project gets to a certain part in it's progress. 

```
2020-05-03T12:22:23.990362+00:00 app[web.1]: [Sun May 03 2020 12:22:23 GMT+0000 (Coordinated Universal Time)] ERROR TypeError: Converting circular structure to JSON
2020-05-03T12:22:23.990366+00:00 app[web.1]:     --> starting at object with constructor 'Timeout'
2020-05-03T12:22:23.990366+00:00 app[web.1]:     |     property '_idlePrev' -> object with constructor 'TimersList'
2020-05-03T12:22:23.990367+00:00 app[web.1]:     --- property '_idleNext' closes the circle
2020-05-03T12:22:23.990367+00:00 app[web.1]:     at JSON.stringify (<anonymous>:null:null)
2020-05-03T12:22:23.990368+00:00 app[web.1]:     at Brain.<anonymous> (/app/node_modules/hubot-redis-brain/src/redis-brain.js:93:42)
2020-05-03T12:22:23.990368+00:00 app[web.1]:     at Brain.emit (events.js:310:20)
2020-05-03T12:22:23.990369+00:00 app[web.1]:     at Brain.save (/app/node_modules/hubot/src/brain.js:102:10)
2020-05-03T12:22:23.990369+00:00 app[web.1]:     at Timeout._onTimeout (/app/node_modules/hubot/src/brain.js:134:14)
2020-05-03T12:22:23.990369+00:00 app[web.1]:     at listOnTimeout (internal/timers.js:549:17)
2020-05-03T12:22:23.990370+00:00 app[web.1]:     at processTimers (internal/timers.js:492:7)
```

**Comment by loleg** [comment]
I don't think this is an issue with hubot or [hubot-redis-brain](https://github.com/hubotio/hubot-redis-brain). This is probably this section of `dribdat.coffee` (line 91):

`robot.brain.set 'eventInfo', eventInfo`

with this variable populated by an API that might be wonky.
